theme = "penumbra+"

[editor]
true-color = true  # ??
color-modes = true # ??
line-number = "relative"
rulers = [80]
shell = ["zsh", "-c"]

[editor.indent-guides]
render = true
character = "▏"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# https://github.com/helix-editor/helix/discussions/5764
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
