# Do not insert newline between shell prompts
add_newline = false

[character]
# Replace the symbol in the prompt with жалкий америконский доллар
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[git_branch]
# Do not show branch icon
format = "on [$branch(:$remote_branch)]($style) "

[purescript]
# Icon for PureScript
symbol = "  "

[scala]
# Icon for Scala
symbol = " "

[zig]
# Icon for Zig
symbol = " "
